Chunky Turtle Logic Rework
Seniorendi/AdvancedPeripherals pull request #582
Opened 2024-04-14 16:33 UTC by zyxkad

#576

1.19.2 version

2024-04-14 16:43 UTC, zyxkad commented
Alr, a lot of things need to change for 1.19.2, will work on it later

2024-04-22 06:32 UTC, SirEndii commented
Is this PR ready for review?

2024-04-22 13:33 UTC, zyxkad commented
yes

2024-04-22 14:07 UTC, SirEndii requested changes

2024-04-22 14:07 UTC, SirEndii commented on src/main/java/de/srendi/advancedperipherals/common/addons/computercraft/turtles/TurtleChunkyUpgrade.java
> +            updateTick++;
This currently does not seem to do anything
Shouldn't it be removed or commented out

2024-04-22 14:12 UTC, SirEndii approved these changes

2024-04-22 14:12 UTC, merged