Update 1.21 config file
Seniorendi/AdvancedPeripherals pull request #676
Opened 2024-12-27 05:15 UTC by diemoell

Updated configuration file code to 1.21

2024-12-29 02:16 UTC, SirEndii commented on src/main/java/de/srendi/advancedperipherals/common/configuration/APConfig.java
> +    // public static final ConfigFileHandler CONFIG_FILE_HANDLER = new ConfigFileHandler();
Feel free to remove that old stuff, I don't think we need that anymore

I hope the stuff using `APConfigHelper.getAPConfigFilePath` works to change the directory. But we will see when this stuff is buildable

2024-12-29 02:16 UTC, SirEndii requested changes

2024-12-29 02:16 UTC, SirEndii commented on src/main/java/de/srendi/advancedperipherals/common/configuration/APConfig.java
>      /*@Override
This can also be removed

2025-01-01 07:32 UTC, diemoell commented
Close this submission and transfer all changes to #677

2025-01-01 07:32 UTC, closed without merging