Moving towards 1.21 update
Seniorendi/AdvancedPeripherals pull request #677
Opened 2024-12-30 18:07 UTC by diemoell

Some EventBusSubscriber, ResourceLocation and ServerTickEvent related code has been updated to 1.21, but the network and the new Data Component still need to be changed

2025-01-01 07:05 UTC, zyxkad commented
@diemoell This have some commits duplicated with #676 .
Can you make all the change in #676? or do not include duplicate commits here.
If #676's change is mandatory, and you want to keep them separate, can you open this after #676 get merged?

2025-01-01 07:32 UTC, diemoell commented
> @diemoell这有一些与#676重复的提交。你可以在#676 中进行所有更改吗？或者不要在这里包含重复的提交。 如果[#676的更改是前面的，并且你想将它们分开，那么你能在](https://github.com/IntelligenceModding/AdvancedPeripherals/pull/676)#676合并后打开它吗？[](https://github.com/IntelligenceModding/AdvancedPeripherals/pull/676)[](https://github.com/IntelligenceModding/AdvancedPeripherals/pull/676)[](https://github.com/IntelligenceModding/AdvancedPeripherals/pull/676)
> 
> 否则，提交和合并消息就会很混乱。

Okay, I'll close #676 and commit all changes here

2025-01-02 01:07 UTC, SirEndii requested changes

2025-01-02 01:07 UTC, SirEndii commented on src/main/java/de/srendi/advancedperipherals/common/addons/refinedstorage/RefinedStorage.java
> +        api.getNetworkNodeRegistry().add(ResourceLocation.fromNamespaceAndPath(AdvancedPeripherals.MOD_ID, "rs_bridge"), (tag, world, pos) -> read(tag, new RefinedStorageNode(world, pos)));
Moving to `AdvancedPeripherals.getRL` would be neat

2025-01-02 01:07 UTC, SirEndii commented on src/main/java/de/srendi/advancedperipherals/common/addons/refinedstorage/RefinedStorageNode.java
> +        return ResourceLocation.fromNamespaceAndPath(AdvancedPeripherals.MOD_ID, "rs_bridge");
Moving to `AdvancedPeripherals.getRL` would be neat

2025-01-02 01:07 UTC, SirEndii commented on src/main/java/de/srendi/advancedperipherals/common/container/InventoryManagerScreen.java
> +        return ResourceLocation.fromNamespaceAndPath(AdvancedPeripherals.MOD_ID, "textures/gui/inventory_manager_gui.png");
Moving to `AdvancedPeripherals.getRL` would be neat

2025-01-02 01:07 UTC, SirEndii commented on src/main/java/de/srendi/advancedperipherals/client/ClientRegistry.java
> +            event.register(new ModelResourceLocation(ResourceLocation.fromNamespaceAndPath(AdvancedPeripherals.MOD_ID, model), "inventory"));
Moving to `AdvancedPeripherals.getRL` would be neat

2025-01-02 21:00 UTC, SirEndii commented
LGTM

2025-01-02 21:00 UTC, merged